apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway-restapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-restapp
  template:
    metadata:
      labels:
        app: gateway-restapp
    spec:
      containers:
        - name: gateway-service
          image: 19269506/swiggy-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: # Setting Environmental Variables
           - name: SPRING_PROFILES_ACTIVE
             value: dev
           - name: EUREKA_SERVER
             valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-restapp
spec:
  type: NodePort
  selector:
    app: gateway-restapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30165